name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for opening an issue. Sam Varghese will check this out soon, and will try to sort this out as soon as possible.'
        pr-message: 'Thanks for submitting your first pull request to this repository. Sam Varghese will check this out soon, and will merge it if it enhances the project. Appreciate you for all you time and efforts on improving this project! 🙂🎉'
